---

python_command: "python"

required_overcloud_repos:
  - "rhel-7-server-rpms"
  - "rhel-7-server-extras-rpms"
  - "rhel-7-server-rh-common-rpms"
  - "rhel-7-server-satellite-tools-6.3-rpms"
  - "rhel-ha-for-rhel-7-server-rpms"
  - "rhel-7-server-openstack-13-deployment-tools-rpms"
  - "rhel-7-server-openstack-13-rpms"
