---
- block:
#  - name: redeployment of directoryvm
#    shell: |
#      ssh dci@192.168.100.2 'rollback.sh -y -n directorvm'

  - local_action: wait_for port=22 host='directorvm' search_regex=OpenSSH delay=10

#  - name: Add undercloud to inventory
#    add_host:
#      name: "undercloud"
#      ansible_fqdn: "{{ '{{' }} undercloud_ip {{ '}}' }}"
#      ansible_user: "stack"
#      ansible_host: "{{ '{{' }} undercloud_ip {{ '}}' }}"
#
#  - copy:
#      src: /var/www/html/dci_repo/dci_repo.repo
#      dest: /etc/yum.repos.d/dci.repo
#    delegate_to: "undercloud"
#    become: True

  - name: configure the undercloud host and start the undercloud
    shell: |
      ansible-playbook undercloud.yaml -i inventory/lab.yml -e @/etc/dci-ansible-agent/settings.yml
    args:
      chdir: '{{ dci_automation_repo_full }}' 

  - name: Overcloud deployment
    shell: |
      ansible-playbook overcloud.yaml -i inventory/lab.yml -e @/etc/dci-ansible-agent/settings.yml
    args:
      chdir: '{{ dci_automation_repo_full }}' 

