---
####################
# Notes on example
####################
#
# I used theforman to generate the testing environment. Variables that were pulled
# from outside theforman were dumped into /etc/dci-openstack-agent/non-theforeman-dci-vars.yml
# and variables pulled from theforman are in /etc/dci-openstack-agent/non-theforeman-dci-vars.yml.
# I'm throwing them all here for an example of all that is needed if doing things manually.


##############################################################
# Environment variables not currently provided by theforeman
##############################################################

# Made up (and availble) ironic provisioning network.
ironic_provisioning_network: "192.168.201.0/24"

# Used to create an eth1.327 vlan interface on the undercloud box for ipmi comms.
ipmi_vlan: 327
ipmi_network_cidr: 172.20.8.0/22
undercloud_ipmi_ip: 172.20.9.100

# rhn credentials used for image pulls
rhsm_user: "removed"
rhsm_pass: "removed"
rhsm_pool: 
  - "removed"
  - "removed"

# rhn service account credentials used for docker registry access.
# Generated from the access.redhat.com page.
rhregistry_user: "removed"
rhregistry_pass: "removed"


# I don't have assignment of external network ips set up from the phobos ironic
# network yet.  We are already pulling a vip, but we need 3 more ip addresses for
# the controller nodes.  The following command was used to allocate 3 more for this
# lab within phobos's ironic network in which these nodes were created.
#
# openstack port create --network ironic --enable lab1controller
external_controller_ips:
  - 172.20.41.57
  - 172.20.41.47
  - 172.20.41.59
external_network_cidr: 172.20.40.0/22
external_network_gateway: 172.20.40.1


# Each environment's network is different. (used to decide which custom-nic templates to use)
lab_network_environment: "phobos_ironic_on_ironic"

# Each environment may have a different disk layout and config. 
# We are using this to decide which template to render.
lab_ceph_config: "phobos_storage_perf"


#####################################################
# Environment variables auto-generated by theforman
#####################################################

# theforman domain level info
domain_name: "lab1.phobos.rpc.rackspace.com"
external_floating_ip: "172.20.41.41"
external_vrid: "13"
internal_floating_ip: "172.20.64.10"
internal_vrid: "12"

# theforeman subnet info tied to the domain
internal_gateway: "172.20.64.1"
internal_network: "172.20.64.0"
internal_netmask: "255.255.252.0"
internal_network_cidr: "172.20.64.0/22"
internal_vlan: "289"
internal_dhcp_from: "172.20.64.50"
internal_dhcp_to: "172.20.64.255"

stor_mgmt_gateway: "172.20.68.1"
stor_mgmt_network: "172.20.68.0"
stor_mgmt_netmask: "255.255.252.0"
stor_mgmt_network_cidr: "172.20.68.0/22"
stor_mgmt_vlan: "290"
stor_mgmt_dhcp_from: "172.20.68.50"
stor_mgmt_dhcp_to: "172.20.68.255"

storage_gateway: "172.20.72.1"
storage_network: "172.20.72.0"
storage_netmask: "255.255.252.0"
storage_network_cidr: "172.20.72.0/22"
storage_vlan: "291"
storage_dhcp_from: "172.20.72.50"
storage_dhcp_to: "172.20.72.255"

tenant_gateway: "172.20.76.1"
tenant_network: "172.20.76.0"
tenant_netmask: "255.255.252.0"
tenant_network_cidr: "172.20.76.0/22"
tenant_vlan: "292"
tenant_dhcp_from: "172.20.76.50"
tenant_dhcp_to: "172.20.76.255"

lbaas_gateway: "172.20.80.1"
lbaas_network: "172.20.80.0"
lbaas_netmask: "255.255.252.0"
lbaas_network_cidr: "172.20.80.0/22"
lbaas_vlan: "293"
lbaas_dhcp_from: "172.20.80.50"
lbaas_dhcp_to: "172.20.80.255"

inside_net_gateway: "172.20.84.1"
inside_net_network: "172.20.84.0"
inside_net_netmask: "255.255.252.0"
inside_net_network_cidr: "172.20.84.0/22"
inside_net_vlan: "294"
inside_net_dhcp_from: "172.20.84.50"
inside_net_dhcp_to: "172.20.84.255"

gw_net_gateway: "172.20.88.1"
gw_net_network: "172.20.88.0"
gw_net_netmask: "255.255.252.0"
gw_net_network_cidr: "172.20.88.0/22"
gw_net_vlan: "295"
gw_net_dhcp_from: "172.20.88.50"
gw_net_dhcp_to: "172.20.88.255"

manilla_gateway: "172.20.92.1"
manilla_network: "172.20.92.0"
manilla_netmask: "255.255.252.0"
manilla_network_cidr: "172.20.92.0/22"
manilla_vlan: "298"
manilla_dhcp_from: "172.20.92.50"
manilla_dhcp_to: "172.20.92.255"


# ironic nodes that have been "checked out" for this environment
# The 'name' can be mapped back to an ironic node id in the
# ironic environment this was spun up on.
ironic_nodes:
  - pm_password: "removed"
    name: "controller01.lab1.phobos.rpc.rackspace.com"
    role: "Controller"
    profile: "control"
    node_index: 0
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c1:48']"
    memory: "257838"
    disk: "558"
    local_gb: "557"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "controller02.lab1.phobos.rpc.rackspace.com"
    role: "Controller"
    profile: "control"
    node_index: 1
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c0:a0']"
    memory: "257838"
    disk: "558"
    local_gb: "557"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "controller03.lab1.phobos.rpc.rackspace.com"
    role: "Controller"
    profile: "control"
    node_index: 2
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c6:b8']"
    memory: "257838"
    disk: "558"
    local_gb: "557"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "compute01.lab1.phobos.rpc.rackspace.com"
    role: "Compute"
    profile: "compute"
    node_index: 0
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c6:e8']"
    memory: "257838"
    disk: "558"
    local_gb: "557"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "compute02.lab1.phobos.rpc.rackspace.com"
    role: "Compute"
    profile: "compute"
    node_index: 1
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c6:68']"
    memory: "257838"
    disk: "558"
    local_gb: "557"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "ceph01.lab1.phobos.rpc.rackspace.com"
    role: "CephStorage"
    profile: "ceph-storage"
    node_index: 0
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c0:e8']"
    memory: "131072"
    disk: "745"
    local_gb: "744"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "ceph02.lab1.phobos.rpc.rackspace.com"
    role: "CephStorage"
    profile: "ceph-storage"
    node_index: 1
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:c8:a8']"
    memory: "131072"
    disk: "745"
    local_gb: "744"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"
  - pm_password: "removed"
    name: "ceph03.lab1.phobos.rpc.rackspace.com"
    role: "CephStorage"
    profile: "ceph-storage"
    node_index: 2
    phobos_ironic_node_id: "removed"
    pm_type: "pxe_ipmitool"
    pm_addr: "removed"
    mac: "['9c:dc:71:d6:20:90']"
    memory: "131072"
    disk: "745"
    local_gb: "744"
    arch: "x86_64"
    cpu: "32"
    pm_user: "root"

