# Usage: 
#  . /home/stack/stackrc
#  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /usr/bin/tripleo-ansible-inventory /home/stack/playbooks/register_overcloud.yml
#
# Info gathered from section 5.9 in the osp16.1 docs:
#  https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/advanced_overcloud_customization/ansible-based-registration
---
- name: register all overcloud nodes
  hosts: overcloud
  become: true
  vars_files:
    - /home/stack/templates/rhsm.yaml
  tasks:
    - name: Register system
      redhat_subscription:
        username: '{{ parameter_defaults.RhsmVars.rhsm_username }}'
        password: '{{ parameter_defaults.RhsmVars.rhsm_password }}'
        pool_ids: '{{ parameter_defaults.RhsmVars.rhsm_pool_ids }}'
    - name: Disable all repos
      command: "subscription-manager repos --disable *"
    - name: Enable current list of repos
      command: "subscription-manager repos --enable {{ item }}"
      with_items: '{{ parameter_defaults.RhsmVars.rhsm_repos }}'

