# Usage: 
#  . /home/stack/stackrc
#  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /usr/bin/tripleo-ansible-inventory /home/stack/playbooks/unregister_overcloud.yml
#
# Info gathered from section 5.9 in the osp16 docs:
#  https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/advanced_overcloud_customization/ansible-based-registration
---
- name: Unregister all overcloud nodes
  hosts: overcloud
  become: true
  tasks:
    - name: Unregister the system
      shell: |
        /usr/bin/subscription-manager remove --all
        /usr/bin/subscription-manager unregister
        /usr/bin/subscription-manager clean

