---
- include: create_playbooks_dir.yml

- name: Create a fencing script with available data
  template:
    src: configure_fencing.sh.j2
    dest: /home/stack/playbooks/configure_fencing.sh
    owner: stack
    group: stack
    mode: 0750
  tags:
    - configure_fencing

- name: Copy the fencing playbook over
  copy:
    src: configure_fencing.yml
    dest: /home/stack/playbooks/configure_fencing.yml 
  tags:
    - configure_fencing

- name: Pause for 1 minute to give ironic time to clean the nodes after enrollement and inspection
  pause:
    minutes: 1
  tags:
    - configure_fencing

- name: Run the ansible playbook to configure fencing from the director vm
  shell: |
    . /home/stack/stackrc
    export ANSIBLE_HOST_KEY_CHECKING=false
    stdbuf -i0 -e0 -o0 ansible-playbook -i /usr/bin/tripleo-ansible-inventory /home/stack/playbooks/configure_fencing.yml -b | tee configure_fencing.log
  tags:
    - configure_fencing
