---

# These templates are based off of https://one.rackspace.com/display/OPC/OSP13+Deployment+Guide

- name: Pull the undercloud ca cert into a variable for use in the templates
  slurp:
    src: "/etc/pki/ca-trust/source/anchors/director-ca.crt"
  register: caslurp
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Set the director_ca_cert variable from the contents.
  set_fact:
    director_ca_cert: "{{ caslurp['content'] | b64decode }}"
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Pull the undercloud ca cert into a variable for use in the templates
  slurp:
    src: "/etc/pki/ca-trust/source/anchors/cm-local-ca.pem"
  register: caslurp
  when: not enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Set the director_ca_cert variable from the contents.
  set_fact:
    director_ca_cert: "{{ caslurp['content'] | b64decode }}"
  when: not enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Pull the overcloud cert into a variable for use in the templates
  slurp:
    src: "{{ ssl_working_dir }}/{{ overcloud_endpoint_fqdn }}.crt"
  register: overcloudcrtslurp
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Set the overcloud_cert variable from the contents.
  set_fact:
    overcloud_cert: "{{ overcloudcrtslurp['content'] | b64decode }}"
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Pull the overcloud key into a variable for use in the templates
  slurp:
    src: "{{ ssl_working_dir }}/{{ overcloud_endpoint_fqdn }}.key"
  register: overcloudkeyslurp
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Set the overcloud_key variable from the contents.
  set_fact:
    overcloud_key: "{{ overcloudkeyslurp['content'] | b64decode }}"
  when: enable_self_signed_certs 
  tags:
    - overcloud_env_templates

- name: Set up the /home/stack/templates/<envfile>.yaml environment files
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/{{ item }}.yaml.j2
    dest: /home/stack/templates/{{ item }}.yaml
  with_items:
    - "00-node-info"
    - "31-inject-trust-anchor-hiera"
    - "20-network-environment"
    - "40-ips-from-pool-all"
  tags:
    - overcloud_env_templates

- name: Create /home/stack/templates/custom-nics
  file:
    state: directory
    path: /home/stack/templates/custom-nics
    owner: stack
    group: stack
    mode: '0750'
  tags:
    - overcloud_env_templates

- name: Copy all of the environment specific nic configs over
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/{{ lab_network_environment }}-custom-nics/{{ item }}.yaml
    dest: /home/stack/templates/custom-nics/{{ item }}.yaml
    owner: stack
    group: stack
    mode: '0644'
  with_items:
    - controller
    - compute
    - ceph-storage
  tags:
    - overcloud_env_templates


- name: Create /home/stack/templates/roles
  file:
    state: directory
    path: /home/stack/templates/roles
    owner: stack
    group: stack
    mode: '0750'
  tags:
    - overcloud_env_templates

- name: Generate the /home/stack/roles_data.yaml file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/roles/roles_data.yaml
    dest: /home/stack/templates/roles/roles_data.yaml
    owner: stack
    group: stack
    mode: '0644'
  tags:
    - overcloud_env_templates


- name: Set up the /home/stack/templates/33-enable-tls.yaml environment file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/33-enable-tls.yaml.j2
    dest: /home/stack/templates/33-enable-tls.yaml
  when: enable_self_signed_certs
  # we can add another here when testing user provided certs later on
  tags:
    - overcloud_env_templates


- name: Set up the /home/stack/templates/55-octavia.yaml environment file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/55-octavia.yaml.j2
    dest: /home/stack/templates/55-octavia.yaml
  when: enable_octavia
  tags:
    - overcloud_env_templates

- name: Set up the /home/stack/templates/50-ceph-ansible.yaml environment file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/50-ceph-ansible.yaml.j2
    dest: /home/stack/templates/50-ceph-ansible.yaml
  when: enable_ceph
  tags:
    - overcloud_env_templates

- name: Set up the /home/stack/templates/51-ceph-config.yaml environment file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/{{ lab_ceph_config }}-51-ceph-config.yaml.j2
    dest: /home/stack/templates/51-ceph-config.yaml
  when: enable_ceph
  tags:
    - overcloud_env_templates

- name: Set up the /home/stack/templates/52-ceph-rgw.yaml environment file
  template:
    src: home_stack_templates_{{ dci_topic | lower }}/52-ceph-rgw.yaml.j2
    dest: /home/stack/templates/52-ceph-rgw.yaml
  when: enable_ceph
  tags:
    - overcloud_env_templates
