---
# Starting with the "Obtaining images for overcloud nodes"
# section here: https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/director_installation_and_usage/installing-the-undercloud


# Pull in variables based on dci topic
- name: Pull in variables based on dci topic
  include_vars: "{{lookup('first_Found', params)}}"
  vars:
    params:
      files:
        - '{{ dci_topic | lower }}.yml'
      paths:
        - 'vars'
      skip: True
  tags:
    - always

- include: repo_check.yml

# Following redhat doc: https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/director_installation_and_usage/creating-a-basic-overcloud-with-cli-tools

- include: register_ironic_nodes.yml

- include: validations_pre_introspection.yml
  when: "dci_topic | lower == 'osp16'"

- include: run_introspection.yml

- include: setup_ssl_certs.yml

- include: generate_templates.yml
  when: "dci_topic | lower == 'osp16'"

- include: generate_templates_osp13.yml
  when: "dci_topic | lower == 'osp13'"

- include: generate_scripts.yml
  when: "dci_topic | lower == 'osp16'"

- include: generate_scripts_osp13.yml
  when: "dci_topic | lower == 'osp13'"

- include: public_endpoint_hosts.yml

- include: validations_pre_deploy.yml
  when: "dci_topic | lower == 'osp16'"

- include: container_image_prepare_osp13.yml
  when: "dci_topic | lower == 'osp13'"

- include: run_overcloud_deploy.yml

- include: validations_post_deploy.yml
  when: "dci_topic | lower == 'osp16'"

# Post configuration steps below
- include: configure_fencing.yml

- include: config_etc_hosts.yml

- include: update_octavia_quotas.yml

- include: generate_openstacksdk_config.yml

- include: overcloud_network.yml
