---
- name: Copy the script to /home/stack/scripts/overcloud_network.sh
  template:
    src: overcloud_network.sh.j2
    dest: /home/stack/scripts/overcloud_network.sh 
    owner: stack
    group: stack
    mode: 0750
  tags:
    - overcloud_network

- name: Run the script
  shell: stdbuf -i0 -o0 -e0 /home/stack/scripts/overcloud_network.sh | tee /home/stack/overcloud_network.log
  tags:
    - overcloud_network


