---
- name: Generate the rhsm.yaml template
  template:
    src: home_stack_templates/rhsm.yaml.j2
    dest: /home/stack/templates/rhsm.yaml
  tags:
    - overcloud_registration

- include: create_playbooks_dir.yml

- name: Copy the registration helper playbook over
  copy:
    src: register_overcloud.yml
    dest: /home/stack/playbooks/register_overcloud.yml
  tags:
    - overcloud_registration

- name: Copy the unregistration helper playbook over
  copy:
    src: unregister_overcloud.yml
    dest: /home/stack/playbooks/unregister_overcloud.yml
  tags:
    - overcloud_registration
