---

- name: Generate the ironic node import file
  template:
    src: instackenv.json.j2
    dest: /home/stack/instackenv.json
  tags:
    - register_ironic_nodes

- name: Check if import needs ran
  shell: |
    . /home/stack/stackrc
    if [ "$(openstack baremetal node list)" == "" ];then
        echo "run import"
    fi
  register: runimport
  tags:
    - register_ironic_nodes

- name: Validate the file for import
  shell: |
    . /home/stack/stackrc
    openstack overcloud node import --validate-only /home/stack/instackenv.json
  when: runimport.stdout == "run import"
  register: jsonvalidate
  tags:
    - register_ironic_nodes

- name: Run the import if it needs it and validation checks out
  shell: |
    . /home/stack/stackrc
    openstack overcloud node import /home/stack/instackenv.json
  when: runimport.stdout == "run import" and jsonvalidate.rc == 0 
  register: jsonvalidate
  tags:
    - register_ironic_nodes

