---
#- name: Some fuckery is afoot with the new redhat registry login. Lets make sure it is on the undercloud node.
#  shell: podman login registry.redhat.io --username "{{ rhregistry_user }}" --password "{{ rhregistry_pass }}"
#  tags:
#    - run_overcloud_deploy

#- name: Pause for 25 minutes to give ironic time to clean the nodes after enrollement and inspection
#  pause:
#    minutes: 25
#  tags:
#    - run_overcloud_deploy

- name: Run the overcloud deployment
  shell:
    stdbuf -i0 -o0 -e0 ./scripts/deploy_overcloud.sh 2>&1 | tee /home/stack/deploy_overcloud.log
  args:
    creates: /home/stack/overcloudrc
    chdir: /home/stack/
  until: result is not failed
  register: result
  retries: 3
  delay: 300
#  async: 14400
#  poll: 30
#  register: overcloud_deploy
  tags:
    - run_overcloud_deploy
