---

- name: enable ceph tools repo
  rhsm_repository:
    name: '{{ ceph_tools_repo }}'
    state: enabled
  become: True
  when: enable_ceph
  tags:
    - install_ceph_ansible

- name: Install ceph ansible package
  dnf:
    name: '{{ ceph_ansible_pkg_name }}'
    state: present
  become: True
  when: enable_ceph
  tags:
    - install_ceph_ansible

