---

# Pull in variables based on dci topic
- name: Pull in variables based on dci topic
  include_vars: "{{lookup('first_Found', params)}}"
  vars:
    params:
      files:
        - '{{ dci_topic | lower }}.yml'
      paths:
        - 'vars'
      skip: True
  tags:
    - always

- include: undercloud_registration.yml

# Redhat docs skimp on the network config

- include: network_config.yml



# Steps followed from: https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/director_installation_and_usage/preparing-for-director-installation

- include: preparing_the_undercloud.yml

- include: install_ceph_ansible.yml

- include: preparing_container_images.yml
  when: "dci_topic | lower == 'osp16'"

# Redhat docs don't cover the ssl cert generation

- include: setup_ssl_certs.yml


# PCI hardening related configuration
- include: pci_config.yml

# Steps below followed from https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/director_installation_and_usage/installing-the-undercloud

- include: configuring_the_director.yml

- include: validations_pre_undercloud_install.yml
  when: "dci_topic | lower == 'osp16'"

- include: openstack_undercloud_install.yml

- include: overcloud_image_prep.yml

- include: add_exnet_masquerade.yml

