---

# Skipping stack user setup done via cloud-init

- name: Create directories for system images and heat templates
  file:
    state: directory
    path: "/home/stack/{{ item }}"
  with_items:
    - images
    - templates
  tags:
    - undercloud_prep


# Skipping hostname setup done via cloud-init


- name: Add entry into /etc/hosts (must match pub api ip of undercloud)
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ ironic_provisioning_network.split('.')[0:3] | join('.') }}.1"
    line: "{{ ironic_provisioning_network.split('.')[0:3] | join('.') }}.1 directorvm.{{ domain_name }} directorvm directorvm.ctlplane"
  become: True
  tags:
    - undercloud_prep

# Skipping registration done via cloud-init

- name: Update and reboot if needed.
  yum:
    name: "*"
    state: latest
    update_cache: yes
  register: systemupdate
  become: True
  tags:
    - undercloud_prep

- name: Reboot if an update was applied
  reboot:
    reboot_timeout: 3600
  when: systemupdate.changed
  become: True
  tags:
    - undercloud_prep


- name: Install python tripleoclient package
  yum:
    name: '{{ tripleoclient_pkg_name }}'
    update_cache: yes
    state: present
  become: True
  tags:
    - undercloud_prep



