---
- name: Create an environment file with repo credentials
  template:
    src: "container_overrides.yaml.j2"
    dest: "/home/stack/templates/container_overrides.yaml"
    owner: "stack"
    group: "stack"
    mode: '0400'
  tags:
    - prepare_container_images


- name: Prepare container images
  shell: |
    openstack tripleo container image prepare default \
      --local-push-destination \
      --output-env-file /home/stack/containers-prepare-parameter.yaml
  args:
    creates: /home/stack/containers-prepare-parameter.yaml
  tags:
    - prepare_container_images
