---
- name: Pre-auth against the repo to rule out prep issues seen during testing
  shell: |
    podman pull registry.redhat.io/rhel8/rsyslog > /dev/null
    if [ $? != 0 ]; then
      podman login --username "{{ rhregistry_user }}" --password "{{ rhregistry_pass }}" registry.redhat.io
    fi
  tags:
    - prepare_container_images

- name: Create an environment file with repo credentials
  template:
    src: "container_overrides.yaml.j2"
    dest: "/home/stack/templates/container_overrides.yaml"
    owner: "stack"
    group: "stack"
    mode: '0400'
  tags:
    - prepare_container_images

- name: Prepare container images
  shell: |
    openstack tripleo container image prepare default \
      --local-push-destination \
      --output-env-file /home/stack/containers-prepare-parameter.yaml
  args:
    creates: /home/stack/containers-prepare-parameter.yaml
  tags:
    - prepare_container_images
