---
- name: Force a time sync
  shell: |
    # Force a time sync as it can muck with the registration
    systemctl restart chronyd
    sleep 5
    chronyc -a 'burst 4/4'

  become: True
  tags:
    - undercloud_registration

- name: Make sure the system is registered.
  redhat_subscription:
    state: present
    username: '{{ rhsm_user }}'
    password: '{{ rhsm_pass }}'
    pool_ids: '{{ rhsm_pool }}'
#    force_register: yes
    server_insecure: yes
  become: True
  ignore_errors: True
  tags:
    - undercloud_registration

- name: Make sure all the required repos are in place
  rhsm_repository:
    name: '{{ item }}'
    state: enabled
  become: True
  with_items: '{{ undercloud_repositories }}'
  tags:
    - undercloud_registration

