---

# enable/disable vars
enable_ceph: true
enable_self_signed_certs: true
enable_pci: true
enable_dci_image_repo: true
enable_undercloud_debug: false




# default vars
haproxy_ssl_dir: "/etc/pki/instack-certs"
haproxy_ssl_cert: "{{ haproxy_ssl_dir }}/undercloud.pem"
ssl_working_dir: "/home/stack/sslfiles"
ssl_C: "US"
ssl_ST: "Texas"
ssl_L: "San Antonio"
ssl_O: "RPC-R"
ssl_CN_prefix: "ca"

undercloud_hiera_overrides_file: "heira-overrides.yaml"


# undercloud.conf defaults
undercloud_local_interface: "eth1"
undercloud_local_mtu: "1500"
undercloud_nameservers: "69.20.0.164,69.20.0.196"
undercloud_ntp_servers: "69.20.0.164,69.20.0.196"

######################
# tripleo-validations
######################
# https://docs.openstack.org/tripleo-validations/latest/readme.html

# These are part of the 'prep' group that should be ran before the undercloud install.
prep_group_validations:
  - "512e"                    # Advanced format 512e support
  - "service-status"          # Ensure services state
  - "undercloud-cpu"          # Verify undercloud fits the CPU core requirements.
  - "undercloud-disk-space"   # Verify undercloud fits the disk space requirements
  - "undercloud-ram"          # Verify the undercloud fits the RAM requirements.
  - "undercloud-selinux-mode" # Undercloud SELinux Enforcing Mode Check
#  - "tls-everywhere-prep"    # Registered to freeipa/dns(not used in testing)
  
